// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGWXwuaIKDYdgxJ7jGu44o56GZkusx7fc',
    appId: '1:254147802354:web:b7c50f5d1ebea6e5294c6b',
    messagingSenderId: '254147802354',
    projectId: 'mediheal-fyp-project',
    authDomain: 'mediheal-fyp-project.firebaseapp.com',
    storageBucket: 'mediheal-fyp-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADYCZjROZwz_5kSZMQSmVhv_68kIAjEE0',
    appId: '1:254147802354:android:465ee4e6f56a8a4a294c6b',
    messagingSenderId: '254147802354',
    projectId: 'mediheal-fyp-project',
    storageBucket: 'mediheal-fyp-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyehmHYDEsMkUjGJ_v3gwCPUKVkrJUi5A',
    appId: '1:254147802354:ios:8f76b094ccf2dce9294c6b',
    messagingSenderId: '254147802354',
    projectId: 'mediheal-fyp-project',
    storageBucket: 'mediheal-fyp-project.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyehmHYDEsMkUjGJ_v3gwCPUKVkrJUi5A',
    appId: '1:254147802354:ios:8f76b094ccf2dce9294c6b',
    messagingSenderId: '254147802354',
    projectId: 'mediheal-fyp-project',
    storageBucket: 'mediheal-fyp-project.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGWXwuaIKDYdgxJ7jGu44o56GZkusx7fc',
    appId: '1:254147802354:web:f0052619712cdcf4294c6b',
    messagingSenderId: '254147802354',
    projectId: 'mediheal-fyp-project',
    authDomain: 'mediheal-fyp-project.firebaseapp.com',
    storageBucket: 'mediheal-fyp-project.firebasestorage.app',
  );
}
